version: 3.8

services:
  ktu-pwa:
    build: .
    container_name: ktu-cgpa-pwa
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      - PORT=3000
      - NODE_ENV=production
